name: ZACH Multimedia
favicon: null
layout_spectrum: 0.4806432786863297
typography_spectrum: 0.8712382563389838
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.13951508491300046
  lightness: 0.5294123282656074
  saturation: 0.8324640388600528
  rhythmicContrast: 0.6617025115992874
purpose: []
